# MINGD
# Batch size 1000, Train accuracy 60
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=60)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_60
cuda:0
22-10-06 15:23
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_60.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.111
Number of steps = 500 | Failed to convert = 254 | Time taken = 546.1166100502014
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 96, in forward
    return x1 + x
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.73 GiB already allocated; 17.50 MiB free; 30.42 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 70
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=70)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_70
cuda:0
22-10-06 15:32
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_70.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.240
Number of steps = 500 | Failed to convert = 2 | Time taken = 178.88028979301453
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.27 GiB already allocated; 63.50 MiB free; 30.38 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 75
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=75)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_75
cuda:0
22-10-06 15:35
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_75.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.200
Number of steps = 500 | Failed to convert = 1 | Time taken = 187.20824432373047
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.27 GiB already allocated; 79.50 MiB free; 30.36 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 80
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=80)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_80
cuda:0
22-10-06 15:39
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_80.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.230
Number of steps = 173 | Failed to convert = 0 | Time taken = 76.27191758155823
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.27 GiB already allocated; 135.50 MiB free; 30.31 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 85
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=85)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_85
cuda:0
22-10-06 15:41
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_85.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.174
Number of steps = 272 | Failed to convert = 0 | Time taken = 100.66143083572388
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 91, in forward
    x1 = self.batch_norm2(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 135, in forward
    return F.batch_norm(
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/functional.py", line 2149, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 156.00 MiB (GPU 0; 31.75 GiB total capacity; 29.41 GiB already allocated; 59.50 MiB free; 30.38 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 90
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=90)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_90
cuda:0
22-10-06 15:43
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_90.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.261
Number of steps = 153 | Failed to convert = 0 | Time taken = 68.14112567901611
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 94, in forward
    x1 = self.conv2(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 156.00 MiB (GPU 0; 31.75 GiB total capacity; 29.56 GiB already allocated; 33.50 MiB free; 30.41 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 95
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=95)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_95
cuda:0
22-10-06 15:44
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_95.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.230
Number of steps = 117 | Failed to convert = 0 | Time taken = 40.31676697731018
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 156.00 MiB (GPU 0; 31.75 GiB total capacity; 29.26 GiB already allocated; 53.50 MiB free; 30.39 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 98
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=98)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_98
cuda:0
22-10-06 15:45
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_98.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.516
Number of steps = 500 | Failed to convert = 1 | Time taken = 41.68299150466919
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 31.75 GiB total capacity; 28.95 GiB already allocated; 127.50 MiB free; 30.31 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 99
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='mingd', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=99)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_99
cuda:0
22-10-06 15:46
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_99.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.600
Number of steps = 442 | Failed to convert = 0 | Time taken = 42.921289682388306
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 156, in get_mingd_vulnerability
    delta = mingd(model, X, y, args, target = y*0 + target_i)
  File "/home/user/tingweijing/DI-ting_3-var/src/attacks.py", line 204, in mingd
    preds = model(X_r + delta_r)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 91, in forward
    x1 = self.batch_norm2(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 135, in forward
    return F.batch_norm(
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/functional.py", line 2149, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 152.00 MiB (GPU 0; 31.75 GiB total capacity; 29.17 GiB already allocated; 93.50 MiB free; 30.35 GiB reserved in total by PyTorch)
# RAND
# Batch size 1000, Train accuracy 60
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=60)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_60
cuda:0
22-10-06 15:47
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_60.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.111
Getting random attacks
Number of steps = 50 | Failed to convert = 47 | Time taken = 6.644443035125732
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 70
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=70)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_70
cuda:0
22-10-06 15:48
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_70.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.240
Getting random attacks
Number of steps = 50 | Failed to convert = 16 | Time taken = 5.069514751434326
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 75
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=75)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_75
cuda:0
22-10-06 15:48
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_75.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.200
Getting random attacks
Number of steps = 50 | Failed to convert = 9 | Time taken = 4.478270769119263
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 80
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=80)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_80
cuda:0
22-10-06 15:48
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_80.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.230
Getting random attacks
Number of steps = 50 | Failed to convert = 15 | Time taken = 4.930964231491089
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 85
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=85)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_85
cuda:0
22-10-06 15:49
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_85.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.174
Getting random attacks
Number of steps = 50 | Failed to convert = 16 | Time taken = 5.054795980453491
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 90
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=90)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_90
cuda:0
22-10-06 15:49
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_90.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.261
Getting random attacks
Number of steps = 50 | Failed to convert = 12 | Time taken = 4.13246750831604
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 95
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=95)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_95
cuda:0
22-10-06 15:50
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_95.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.230
Getting random attacks
Number of steps = 50 | Failed to convert = 54 | Time taken = 6.0260398387908936
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 98
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=98)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_98
cuda:0
22-10-06 15:50
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_98.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.516
Getting random attacks
Number of steps = 50 | Failed to convert = 34 | Time taken = 9.018494606018066
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
# Batch size 1000, Train accuracy 99
Namespace(alpha_l_1=1.0, alpha_l_2=0.01, alpha_l_inf=0.001, batch_size=500, combine_ratio=0.5, concat=0, concat_factor=1.0, config_file=None, data_path=None, dataset='CIFAR10', device='cuda:0', distance=None, dropRate=0.0, epochs=50, epsilon_l_1=12, epsilon_l_2=0.5, epsilon_l_inf=0.03137254901960784, experiment='3-var', feature_type='rand', gap=0.001, gpu_id=0, imagenet_architecture='wrn', k=100, lr_max=0.1, lr_min=0.0, lr_mode=1, mode='teacher', model_dataset='CIFAR10', model_id='teacher_normalized', model_type='wrn-28-10', noise_sigma=0.05, normalize=1, num_iter=500, opt_type='SGD', path=None, pseudo_labels=0, randomize=0, regressor_embed=0, restarts=1, resume=0, resume_iter=-1, reverse_train_test=0, seed=0, smallest_adv=1, target_batch_size=1000, target_epoch=0, target_te_acc=0, target_tr_acc=99)
Model Directory: ./models/CIFAR10/model_teacher_normalized_1000
File Directory: ./files/CIFAR10_1000/model_teacher_normalized_tr_acc_99
cuda:0
22-10-06 15:50
No Transform
Files already downloaded and verified
Files already downloaded and verified
No Transform
Files already downloaded and verified
Files already downloaded and verified
Loading model from ./models/CIFAR10/model_teacher_normalized_1000/tr_acc_99.pt
Model: ./models/CIFAR10/model_teacher_normalized_1000 | 	 Test Acc: 0.600
Getting random attacks
Number of steps = 50 | Failed to convert = 49 | Time taken = 11.566309928894043
Traceback (most recent call last):
  File "./src/generate_features.py", line 405, in <module>
    feature_extractor(args)
  File "./src/generate_features.py", line 219, in feature_extractor
    test_d = func(args, test_loader, student)
  File "./src/generate_features.py", line 81, in get_random_label_only
    preds = model(X)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 158, in forward
    attention2 = self.block2(attention1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 114, in forward
    return self.nblockLayer(x)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/DI-ting_3-var/src/model_src/wideresnet.py", line 90, in forward
    x1 = self.conv1(x1)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/tingweijing/env/DIenv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 31.75 GiB total capacity; 29.69 GiB already allocated; 119.50 MiB free; 30.34 GiB reserved in total by PyTorch)
